### ISSUE TITLE
Random test failures

### ISSUE THREAD

**Issue by ianco** [hyperledger/aries-endorser-service#25] opened 2022-11-01 15:41 UTC
When running a full integration test suite some tests periodically fail.

It looks like a timing issue, usually establishing the initial connection between the endorser and author, however occasionally it looks like the transaction trips up.

I already found/fixed a few issues but it looks like there is at least one timing issue still in the integration tests ...

**Comment by Gavinok** [comment] 2024-09-12 00:29
One issue I've seen related to this is an error from the author wallet service

> UTC [1469] FATAL:  sorry, too many clients already

**Comment by esune** [comment] 2024-09-17 18:04
Closing since the issue seems mostly resolved, and it is currently not easily reproducible. Will reopen if/when this becomes more frequent.

**Closed by esune** 2024-09-17 18:04 UTC
